/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projekakhir;

import com.formdev.flatlaf.FlatLightLaf;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author infinix
 */
public class Edit extends javax.swing.JFrame {

    public int id;

    /**
     * Creates new form Edit
     */
    public Edit(int id) {
        this.id = id;
        initComponents();
    }

    public void updateTask() {
        FlatLightLaf.setup();
        try {
            String title = (String) namaUpdate.getText();
            String selectedSubject = null;
            String selectedLevel = (String) levelUpdate.getSelectedItem();
            Date date = dateUpdate.getDate();
            LocalDate taskDate = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            LocalDate today = LocalDate.now();
            if (taskDate.isBefore(today)) {
                JOptionPane.showMessageDialog(this, "Tanggal invalid");
                return;
            }
            SimpleDateFormat fmtr = new SimpleDateFormat("yyyy-MM-dd");
            String dueTo = fmtr.format(date);

            Connection conn = Koneksi.getKoneksi();
            if (title == null) {
                JOptionPane.showMessageDialog(this, "Judul tidak boleh kosong");
            }

            if (sejarah.isSelected()) {
                selectedSubject = "Sejarah";
            } else if (economics.isSelected()) {
                selectedSubject = "Ekonomi";
            } else if (geography.isSelected()) {
                selectedSubject = "Geografi";
            }

            String update = "UPDATE task SET taskName = ?, subject = ?, level = ?, finishDate = ? WHERE id = " + id;
            PreparedStatement ps = conn.prepareStatement(update);

            ps.setString(1, title);
            ps.setString(2, selectedSubject);
            ps.setString(3, selectedLevel);
            ps.setString(4, dueTo);

            int updateStatus = ps.executeUpdate();
            if (updateStatus > 0) {
                JOptionPane.showMessageDialog(this, "Tugas berhasil diperbarui!");
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal memperbarui tugas.");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subjectUpdate = new javax.swing.ButtonGroup();
        schedulePanel1 = new projects.schedulepanel.SchedulePanel();
        namaUpdate = new rojerusan.RSMetroTextPlaceHolder();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sejarah = new javax.swing.JRadioButton();
        geography = new javax.swing.JRadioButton();
        economics = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        levelUpdate = new javax.swing.JComboBox<>();
        update = new javax.swing.JButton();
        dateUpdate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 600));

        schedulePanel1.setBackground(new java.awt.Color(255, 255, 255));

        namaUpdate.setFont(new java.awt.Font("JetBrains Mono", 1, 14)); // NOI18N
        namaUpdate.setPhColor(new java.awt.Color(0, 0, 0));
        namaUpdate.setPlaceholder("Masukkan Judul quiz");

        jLabel1.setText("Subject");

        jLabel2.setText("Due To");

        subjectUpdate.add(sejarah);
        sejarah.setText("Sejarah");

        subjectUpdate.add(geography);
        geography.setText("Geografi");

        subjectUpdate.add(economics);
        economics.setText("Ekonomi");

        jLabel3.setText("Level");

        levelUpdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mudah", "Sedang", "Sulit" }));

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout schedulePanel1Layout = new javax.swing.GroupLayout(schedulePanel1);
        schedulePanel1.setLayout(schedulePanel1Layout);
        schedulePanel1Layout.setHorizontalGroup(
            schedulePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, schedulePanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(schedulePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(geography)
                    .addComponent(levelUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addGroup(schedulePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, schedulePanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dateUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(namaUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(schedulePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sejarah)
                        .addComponent(economics)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        schedulePanel1Layout.setVerticalGroup(
            schedulePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(schedulePanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(namaUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(schedulePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(dateUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sejarah)
                .addGap(28, 28, 28)
                .addComponent(geography)
                .addGap(27, 27, 27)
                .addComponent(economics)
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(levelUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(schedulePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(schedulePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        updateTask();
    }//GEN-LAST:event_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Edit().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dateUpdate;
    private javax.swing.JRadioButton economics;
    private javax.swing.JRadioButton geography;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> levelUpdate;
    private rojerusan.RSMetroTextPlaceHolder namaUpdate;
    private projects.schedulepanel.SchedulePanel schedulePanel1;
    private javax.swing.JRadioButton sejarah;
    private javax.swing.ButtonGroup subjectUpdate;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
