/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projekakhir;

/**
 *
 * @author infinix
 */
public class Filter extends javax.swing.JFrame {
    public String levelFilter;
    public String subjectFilter;
    public String querry;
    public static Leaderboard curr = null;
    /**
     * Creates new form Filter
     */
    public Filter(String levelFilter, String subjectFilter, String querry) {
        this.levelFilter = levelFilter;
        this.subjectFilter = subjectFilter;
        this.querry = querry;
        initComponents();
    }
    
    public void proses(){
        levelFilter = null;
        subjectFilter = null;
        if(sejarah.isSelected()){
            subjectFilter = "sejarah";
        }else if(economics.isSelected()){
            subjectFilter = "economics";
        }
        
        if(Mudah.isSelected()){
            levelFilter = "Mudah";
        }else if(Sedang.isSelected()){
            levelFilter = "Sedang";
        }else if(Sulit.isSelected()){
            levelFilter = "Sulit";
        }
        
        if(levelFilter == null && subjectFilter == null){
            querry = "SELECT username, subject, level, SUM(score) AS totalScore FROM leaderboard GROUP BY username, subject, level ORDER BY subject, level DESC";
        }else if(levelFilter != null && subjectFilter == null){
            querry = "SELECT username, subject, level, SUM(score)AS totalScore FROM leaderboard WHERE level = '" + levelFilter + "' GROUP BY username, subject ORDER BY subject DESC";
        }else if (subjectFilter != null && levelFilter == null){
            querry = "SELECT username, subject, level, SUM(score)AS totalScore FROM leaderboard WHERE subject = '" + subjectFilter + "' GROUP BY username, level ORDER BY level DESC";
        }else{
            querry = "SELECT username, subject, level, SUM(score)AS totalScore FROM leaderboard WHERE subject = '" + subjectFilter + "' AND level = '"+ levelFilter + "' GROUP BY username ORDER BY username DESC";
        }
        
        if (curr != null){
            curr.dispose();
            curr = null;
        }
        curr = new Leaderboard(levelFilter, subjectFilter, querry);
        curr.loadLeaderboardData();
        System.out.println(querry);
        curr.setVisible(true);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Subject = new javax.swing.ButtonGroup();
        Level = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        sejarah = new javax.swing.JRadioButton();
        economics = new javax.swing.JRadioButton();
        Mudah = new javax.swing.JRadioButton();
        Sedang = new javax.swing.JRadioButton();
        Sulit = new javax.swing.JRadioButton();
        Apply = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Subject.add(sejarah);
        sejarah.setText("Sejarah");
        sejarah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sejarahActionPerformed(evt);
            }
        });

        Subject.add(economics);
        economics.setText("Ekonomi");

        Level.add(Mudah);
        Mudah.setText("Mudah");
        Mudah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MudahActionPerformed(evt);
            }
        });

        Level.add(Sedang);
        Sedang.setText("Sedang");
        Sedang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SedangActionPerformed(evt);
            }
        });

        Level.add(Sulit);
        Sulit.setText("Sulit");
        Sulit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SulitActionPerformed(evt);
            }
        });

        Apply.setBackground(new java.awt.Color(102, 255, 255));
        Apply.setText("Apply");
        Apply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApplyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(sejarah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(economics)
                .addGap(96, 96, 96))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(Mudah)
                .addGap(64, 64, 64)
                .addComponent(Sedang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(Sulit)
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Apply)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sejarah)
                            .addComponent(economics))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Sedang)
                            .addComponent(Mudah)
                            .addComponent(Sulit))
                        .addGap(40, 40, 40)))
                .addComponent(Apply)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sejarahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sejarahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sejarahActionPerformed

    private void MudahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MudahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MudahActionPerformed

    private void SulitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SulitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SulitActionPerformed

    private void SedangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SedangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SedangActionPerformed

    private void ApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApplyActionPerformed
        // TODO add your handling code here:
        proses();
        dispose();
    }//GEN-LAST:event_ApplyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Filter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Filter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Filter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Filter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Filter().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Apply;
    private javax.swing.ButtonGroup Level;
    private javax.swing.JRadioButton Mudah;
    private javax.swing.JRadioButton Sedang;
    private javax.swing.ButtonGroup Subject;
    private javax.swing.JRadioButton Sulit;
    private javax.swing.JRadioButton economics;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton sejarah;
    // End of variables declaration//GEN-END:variables
}
