/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projekakhir;

import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.mongodb.client.MongoDatabase;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author infinix
 */
public class HomeStudent extends javax.swing.JFrame {

    public String currentUsername;
    public boolean isDone;
    public int selectedRow = 0;
    public int id;
    private String levelFilter;
    private String subjectFilter;
    private String querry;
    private DefaultTableModel tableModel;
    private Detail dt;
    private Quiz quiz;

    /**
     * Creates new form HomeStudent
     */
    public HomeStudent(String username) {
        this.currentUsername = username;
        FlatLightLaf.setup();
        initComponents();
        history.setVisible(false);
        jPanel1.add(history);
        select.setVisible(false);
        jPanel1.add(select);
        task.setVisible(false);
        jPanel1.add(task);
        Nama.setText(this.currentUsername);
        hy.setText("Welcome " + this.currentUsername);
        historyName.setText("Riwayat Quiz " + currentUsername);
    }

    public void loadTask() {
        tableModel = new DefaultTableModel(new Object[]{"id", "Subject", "Level", "Due to", "Detail"}, 0);
        taskTable.setModel(tableModel);
        try {
            Connection conn = Koneksi.getKoneksi();
            String sql = "SELECT id, subject, level, finishDate FROM task WHERE isDone = '0'";
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            // Tambahkan data dari ResultSet ke tabel
            while (rs.next()) {
                id = rs.getInt("id");
                String Subject = rs.getString("subject");
                String Level = rs.getString("level");
                String DueTo = rs.getString("finishDate");

                // Tambahkan baris baru ke tabel
                tableModel.addRow(new Object[]{id, Subject, Level, DueTo});
            }
            // Tambahkan renderer dan editor ke kolom ke-3 (indeks 3)
            taskTable.getColumnModel().getColumn(4).setCellRenderer(new detailButtonRenderer());
            taskTable.getColumnModel().getColumn(4).setCellEditor(new detailButtonEditor(this, taskTable, new JButton(new FlatSVGIcon("SVGICON/detail.svg", 0.35f))));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal dengan error: " + e.getMessage());
        }
    }

    public int taskSelected() {
        int taskId = 0;
        selectedRow = taskTable.getSelectedRow();
        if (selectedRow >= 0) {
            taskId = (int) taskTable.getValueAt(selectedRow, 0); // Indeks 0 adalah kolom ID
        }
        return taskId;
    }

    public void loadHistory() {
        tableModel = new DefaultTableModel(new Object[]{"Nama", "Subject", "Level", "Score"}, 0);
        History.setModel(tableModel);

        try (Connection connection = Koneksi.getKoneksi()) {
            String sql = "SELECT username, subject, level, score FROM leaderboard WHERE username = '" + currentUsername + "'";
            PreparedStatement preparedStatement = connection.prepareStatement(sql);
            ResultSet resultSet = preparedStatement.executeQuery();
            // Mengisi data ke dalam tabel
            tableModel.setRowCount(0);
            while (resultSet.next()) {
                String Nama = resultSet.getString("username");
                String Subject = resultSet.getString("subject");
                String Level = resultSet.getString("level");
                int Score = resultSet.getInt("Score");

                // Tambahkan baris baru ke tabel
                tableModel.addRow(new Object[]{Nama, Subject, Level, Score});
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Kesalahan saat memuat leaderboard: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        hy = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Nama = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Quiz = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        select = new javax.swing.JPanel();
        level = new javax.swing.JComboBox<>();
        kewarganegaraan = new javax.swing.JRadioButton();
        sejarah = new javax.swing.JRadioButton();
        ekonomi = new javax.swing.JRadioButton();
        play = new javax.swing.JButton();
        geografi = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        history = new javax.swing.JPanel();
        historyName = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        History = new javax.swing.JTable();
        task = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taskTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(249, 247, 228));

        home.setBackground(new java.awt.Color(249, 247, 228));

        hy.setFont(new java.awt.Font("JetBrains Mono", 1, 24)); // NOI18N

        jLabel2.setFont(new java.awt.Font("JetBrains Mono", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Udah belajar belum hari ini?...");

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeLayout.createSequentialGroup()
                .addContainerGap(401, Short.MAX_VALUE)
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hy, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(366, 366, 366))
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeLayout.createSequentialGroup()
                .addContainerGap(305, Short.MAX_VALUE)
                .addComponent(hy, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(381, 381, 381))
        );

        jPanel2.setBackground(new java.awt.Color(18, 45, 79));

        Nama.setBackground(new java.awt.Color(249, 247, 228));
        Nama.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        Nama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton1.setBackground(new java.awt.Color(249, 247, 228));
        jButton1.setText("Leaderboard");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Quiz.setBackground(new java.awt.Color(249, 247, 228));
        Quiz.setText("Quiz");
        Quiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuizActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(249, 247, 228));
        jButton3.setText("To Do");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(249, 247, 228));
        jButton4.setText("History");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(22, 22, 22))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                        .addComponent(Quiz, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(Quiz, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(111, 111, 111))
        );

        select.setBackground(new java.awt.Color(249, 247, 228));

        level.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mudah", "Sedang", "Sulit" }));
        level.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                levelActionPerformed(evt);
            }
        });

        kewarganegaraan.setBackground(new java.awt.Color(249, 247, 228));
        buttonGroup1.add(kewarganegaraan);
        kewarganegaraan.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        kewarganegaraan.setText("Kewarganegaraan");
        kewarganegaraan.setOpaque(true);
        kewarganegaraan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kewarganegaraanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kewarganegaraanMouseExited(evt);
            }
        });
        kewarganegaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kewarganegaraanActionPerformed(evt);
            }
        });

        buttonGroup1.add(sejarah);
        sejarah.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        sejarah.setText("Sejarah");
        sejarah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sejarahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sejarahMouseExited(evt);
            }
        });
        sejarah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sejarahActionPerformed(evt);
            }
        });

        ekonomi.setBackground(new java.awt.Color(249, 247, 228));
        buttonGroup1.add(ekonomi);
        ekonomi.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        ekonomi.setText("Ekonomi");
        ekonomi.setBorderPainted(true);
        ekonomi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ekonomi.setOpaque(true);
        ekonomi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ekonomiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ekonomiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ekonomiMouseExited(evt);
            }
        });
        ekonomi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekonomiActionPerformed(evt);
            }
        });

        play.setBackground(new java.awt.Color(43, 205, 255));
        play.setText("PLAY");
        play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                playMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                playMouseExited(evt);
            }
        });
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });

        buttonGroup1.add(geografi);
        geografi.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        geografi.setText("Geografi");
        geografi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                geografiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                geografiMouseExited(evt);
            }
        });
        geografi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geografiActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("JetBrains Mono", 1, 14)); // NOI18N
        jLabel1.setText("Pilih subjek");

        jLabel3.setFont(new java.awt.Font("JetBrains Mono", 1, 14)); // NOI18N
        jLabel3.setText("Pilih level");

        javax.swing.GroupLayout selectLayout = new javax.swing.GroupLayout(select);
        select.setLayout(selectLayout);
        selectLayout.setHorizontalGroup(
            selectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, selectLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(play, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
            .addGroup(selectLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(selectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(level, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sejarah, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(geografi, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(selectLayout.createSequentialGroup()
                        .addGap(401, 401, 401)
                        .addGroup(selectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kewarganegaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ekonomi, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(347, Short.MAX_VALUE))
        );
        selectLayout.setVerticalGroup(
            selectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, selectLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(selectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sejarah, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kewarganegaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(selectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(geografi, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ekonomi, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(level, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(play, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        history.setBackground(new java.awt.Color(249, 247, 228));

        historyName.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        historyName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        History.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        History.setRowHeight(40);
        History.setShowGrid(true);
        jScrollPane3.setViewportView(History);

        javax.swing.GroupLayout historyLayout = new javax.swing.GroupLayout(history);
        history.setLayout(historyLayout);
        historyLayout.setHorizontalGroup(
            historyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historyLayout.createSequentialGroup()
                .addGroup(historyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(historyLayout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(historyName, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(historyLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(330, Short.MAX_VALUE))
        );
        historyLayout.setVerticalGroup(
            historyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, historyLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(historyName, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        task.setBackground(new java.awt.Color(249, 247, 228));

        taskTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        taskTable.setRowHeight(40);
        taskTable.setShowGrid(true);
        jScrollPane1.setViewportView(taskTable);

        javax.swing.GroupLayout taskLayout = new javax.swing.GroupLayout(task);
        task.setLayout(taskLayout);
        taskLayout.setHorizontalGroup(
            taskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taskLayout.createSequentialGroup()
                .addContainerGap(447, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(204, 204, 204))
        );
        taskLayout.setVerticalGroup(
            taskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1115, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(0, 224, Short.MAX_VALUE)
                    .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(219, 219, 219)
                    .addComponent(select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(115, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(0, 220, Short.MAX_VALUE)
                    .addComponent(task, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(0, 222, Short.MAX_VALUE)
                    .addComponent(history, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(select, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(task, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(history, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        // TODO add your handling code here:
        NoKoneksi koneksiDB = new NoKoneksi();
        Connection conn = Koneksi.getKoneksi();
        MongoDatabase db = koneksiDB.getDatabase();

        if (conn != null) {
            String selectedLevel = (String) level.getSelectedItem();
            String selectedSubject = null;

            // Mendapatkan subject yang dipilih dari RadioButton
            if (sejarah.isSelected()) {
                selectedSubject = "Sejarah";
            } else if (kewarganegaraan.isSelected()) {
                selectedSubject = "Kewarganegaraan";
            } else if (ekonomi.isSelected()) {
                selectedSubject = "Ekonomi";
            } else if (geografi.isSelected()) {
                selectedSubject = "Geografi";
            }

            if (selectedLevel != null && selectedSubject != null) {
                if (db != null) {
                    dt = new Detail(id, currentUsername, isDone);
                    quiz = new Quiz(selectedLevel, selectedSubject, currentUsername, dt);
                    quiz.setVisible(true);
                    System.out.println("" + dt);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Pilih yang benar");
                return;
            }
        }
    }//GEN-LAST:event_playActionPerformed

    private void sejarahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sejarahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sejarahActionPerformed

    private void geografiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geografiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_geografiActionPerformed

    private void playMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playMouseEntered
        // TODO add your handling code here:
        play.setBackground(new Color(0, 102, 255));
    }//GEN-LAST:event_playMouseEntered

    private void playMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playMouseExited
        // TODO add your handling code here:
        play.setBackground(new Color(43, 205, 255));
    }//GEN-LAST:event_playMouseExited

    private void kewarganegaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kewarganegaraanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kewarganegaraanActionPerformed

    private void levelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_levelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_levelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // Menyembunyikan panel select dan menampilkan panel task

        // Logika untuk menampilkan leaderboard
        Filter fr = new Filter(levelFilter, subjectFilter, querry);
        fr.curr = new Leaderboard(levelFilter, subjectFilter, querry);
        fr.curr.loadLeaderboardData();
        fr.curr.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void QuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuizActionPerformed
        // TODO add your handling code here:
        // Menghapus semua komponen dari jPanel1
        // Menampilkan panel select dan menyembunyikan panel task jika ada
        home.setVisible(false);
        history.setVisible(false);
        task.setVisible(false);
        select.setVisible(true);
        jPanel1.add(select);
    }//GEN-LAST:event_QuizActionPerformed

    private void ekonomiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekonomiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ekonomiActionPerformed

    private void ekonomiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ekonomiMouseEntered
        // TODO add your handling code here:
        ekonomi.setBackground(new Color(83, 180, 250));
    }//GEN-LAST:event_ekonomiMouseEntered

    private void ekonomiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ekonomiMouseExited
        // TODO add your handling code here:
        ekonomi.setBackground(select.getBackground());
    }//GEN-LAST:event_ekonomiMouseExited

    private void ekonomiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ekonomiMouseClicked

    }//GEN-LAST:event_ekonomiMouseClicked

    private void kewarganegaraanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kewarganegaraanMouseEntered
        // TODO add your handling code here:
        kewarganegaraan.setBackground(new Color(83, 180, 250));
    }//GEN-LAST:event_kewarganegaraanMouseEntered

    private void kewarganegaraanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kewarganegaraanMouseExited
        // TODO add your handling code here:
        kewarganegaraan.setBackground(select.getBackground());
    }//GEN-LAST:event_kewarganegaraanMouseExited

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        home.setVisible(false);
        history.setVisible(false);
        select.setVisible(false);
        loadTask();
        task.setVisible(true);
        jPanel1.add(task);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                Auth at = new Auth();
        dispose();
        at.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
                home.setVisible(false);
        select.setVisible(false);
        task.setVisible(false);
        loadHistory();
        history.setVisible(true);
        jPanel1.add(history);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void sejarahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sejarahMouseEntered
        // TODO add your handling code here:
        sejarah.setBackground(new Color(83, 180, 250));
    }//GEN-LAST:event_sejarahMouseEntered

    private void sejarahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sejarahMouseExited
        // TODO add your handling code here:
        sejarah.setBackground(select.getBackground());
    }//GEN-LAST:event_sejarahMouseExited

    private void geografiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_geografiMouseEntered
        // TODO add your handling code here:
        geografi.setBackground(new Color(83, 180, 250));
    }//GEN-LAST:event_geografiMouseEntered

    private void geografiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_geografiMouseExited
        // TODO add your handling code here:
        geografi.setBackground(select.getBackground());
    }//GEN-LAST:event_geografiMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HomeStudent(currentUsername).setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable History;
    private javax.swing.JLabel Nama;
    private javax.swing.JButton Quiz;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton ekonomi;
    private javax.swing.JRadioButton geografi;
    private javax.swing.JPanel history;
    private javax.swing.JLabel historyName;
    private javax.swing.JPanel home;
    private javax.swing.JLabel hy;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton kewarganegaraan;
    private javax.swing.JComboBox<String> level;
    private javax.swing.JButton play;
    private javax.swing.JRadioButton sejarah;
    private javax.swing.JPanel select;
    private javax.swing.JPanel task;
    private javax.swing.JTable taskTable;
    // End of variables declaration//GEN-END:variables
}
